name: Build project for Android operating system
on: workflow_dispatch
jobs:
  build-Android:
    name: Build for ${{ matrix.targetPlatform }} with ${{matrix.scriptingBackend}} scripting backend on Linux runner
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android # Build an Android .apk standalone app.
        scriptingBackend:
          - Mono # 0
          - IL2CPP # 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: DragonBoy/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - name: Change scripting backend to ${{matrix.scriptingBackend}}
        run: chmod +x set_scripting_backend.sh && ./set_scripting_backend.sh "DragonBoy/ProjectSettings/ProjectSettings.asset" "${{ matrix.targetPlatform }}" "${{matrix.scriptingBackend}}"
      - if: ${{ matrix.targetPlatform == 'Android' }} 
        name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          androidKeystoreName: DragonBoy-UnityProject.keystore # This file won't exist, but this property needs to exist.
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          projectPath: DragonBoy
          buildName: DragonBoy
          allowDirtyBuild: true
      - name: Upload build results
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}-${{matrix.scriptingBackend}}
          path: build/${{ matrix.targetPlatform }}
