name: Build project for IOS operating system
on: workflow_dispatch
jobs:
  build-IOS:
    name: Build for ${{ matrix.targetPlatform }} with ${{matrix.scriptingBackend}} scripting backend on MacOS runner
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS # Build an iOS player.
        scriptingBackend:
          - IL2CPP # 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: DragonBoy/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - name: Change scripting backend to ${{matrix.scriptingBackend}}
        run: chmod +x set_scripting_backend_mac.sh && ./set_scripting_backend_mac.sh "DragonBoy/ProjectSettings/ProjectSettings.asset" "${{ matrix.targetPlatform }}" "${{matrix.scriptingBackend}}"
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: DragonBoy
          buildName: DragonBoy
          allowDirtyBuild: true
      - name: Upload build results
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}-${{matrix.scriptingBackend}}
          path: build/${{ matrix.targetPlatform }}
