name: Build project for Windows operating system
on: workflow_dispatch
jobs:
  build-Windows:
    name: Build for ${{ matrix.targetPlatform }} with ${{matrix.scriptingBackend}} scripting backend on Windows runner
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - WSAPlayer # Build an Windows Store Apps player.
        scriptingBackend:
          - Mono # 0
          - IL2CPP # 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: DragonBoy/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - name: Change scripting backend to ${{matrix.scriptingBackend}}
        run: pwsh ./set_scripting_backend.ps1 -projectSettingsPath "DragonBoy/ProjectSettings/ProjectSettings.asset" -platform ${{ matrix.targetPlatform }} -scriptingBackend ${{matrix.scriptingBackend}} || powershell ./set_scripting_backend.ps1 -projectSettingsPath "DragonBoy/ProjectSettings/ProjectSettings.asset" -platform ${{ matrix.targetPlatform }} -scriptingBackend ${{matrix.scriptingBackend}};
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: DragonBoy
          buildName: DragonBoy
          allowDirtyBuild: true
      - name: Upload build results
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}-${{matrix.scriptingBackend}}
          path: build/${{ matrix.targetPlatform }}
